### ISSUE TITLE
a problem: java.lang.NullPointerException

### ISSUE THREAD

**Issue by SaraMkh** [Yufei-Yan/k-anonymity-simulator#1]
hi 
from my heart, thank you so much for the k-anonymity-simulator 
it helps me too much 
but I face this problem 
the program cant read the file.txt (like   public static final String WIKI_VOTE_FILE = "/src/resources/DataSets/wiki-Vote.txt";)
the console system show this for me 
2137 [main] DEBUG org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor  - Autowiring by type from bean name 'main.java.App.Main' to bean named 'AppFrame'
2140 [main] ERROR main.java.App.View.AppFrame  - java.lang.NullPointerException
2204 [Thread-1] DEBUG main.java.App.Datasets.DataSetController  - Start load DataSet:Facebook circles
Exception in thread "Thread-1" java.lang.NullPointerException
	at java.io.Reader.<init>(Reader.java:78)
	at java.io.InputStreamReader.<init>(InputStreamReader.java:72)
	at main.java.App.Common.Utils.FileUtil.loadDataSet(FileUtil.java:25)
	at main.java.App.Datasets.DataSetController.loadDataSet(DataSetController.java:69)
	at main.java.App.Common.UITasks.DataSetLoaderTask$1.run(DataSetLoaderTask.java:30)
	at java.lang.Thread.run(Thread.java:745)

**Comment by Yufei-Yan** [comment]
I don't have a function to read a file in this project.
And, by the way, this repo is only for a class demo. The implementation has major issues, which do not completely simulate the k-anonymity idea. 
Thank you for your question, but please do not use this project in a serious case unless you find some useful pieces of codes.

**Comment by SaraMkh** [comment]
No,Thank you for this project
It give me an idea about how implementing the k-anonymous algorithm
I will try to improve it
I am a master student and I need such open source to implement my thesis
idea
But I have few questions, please answer it if you have time
-If you publish a paper or make a report about this tools
Please send me a capy 🤗

-from what I read before, the k-symmestry algorithms  anonymize  the
network structure (do not anonymize the location of the node). I mean your
implementation for the k-symmestry do the same thing, is what I understand
right???

Hopefully,  I do not bother you
Thank you so much for everything you did for me

**Comment by Yufei-Yan** [comment]
Hi, @SaraMkh

We have a report for the project. 
[Final+Project+Report.docx](https://github.com/Yufei-Yan/k-anonymity-simulator/files/1666206/Final.Project.Report.docx)
It's been a year. I don't remember all details. Use it with your own risk.

Let me know if you have more questions.

Thank you.
